# Tomcat
server:
  port: 8021
  servlet:
    context-path: /tigerTeeth

# Spring
spring:
  application:
    # 应用名称
    name: game-tigerTeeth
  profiles:
    # 环境配置
    active: '@profiles.active@'

# 最大连接数
http:
  maxTotal: 100
  # 并发数
  defaultMaxPerRoute: 20
  # 客户端创建连接超时时间
  connectTimeout: 10000
  # 从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  # 服务端响应超时时间
  socketTimeout: 30000
  # 提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
  # 可用空闲连接过期时间,重用空闲连接时会先检查是否空闲时间超过这个时间，如果超过，释放socket重新建立
  validateAfterInactivity: 3000000
